### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Samson11** [ChatAir/ChatAir-Android#12]
Projec is empty.How are we supposed to help with an empty project

**Comment by Mazouzii** [comment]
Yeah, it's empty.
I have an android app, Anyone know how to integrate these features with my app?

**Comment by Testator** [comment]
WTH. I thought it was just me!

**Comment by Testator** [comment]
This shizz empty

**Comment by wajahatkarim3** [comment]
@Samson11 @Mazouzii @Testator We have changed the name to ChatAir now. And we will be releasing the first version before October hopefully. 

Thank you for your patience.
