### ISSUE TITLE
Implement Contacts Screen

### ISSUE THREAD

**Issue by iadeelzafar** [ChatAir/ChatAir-android#19]
**Description:** 
Implement contacts screen. Use the **Contacts Screen Design** from the [designs ](https://github.com/ChatAir/ChatAir-android/tree/master/designs)folder as a reference.

**Comment by droid-it** [comment]
Is it open to be picked up? If yes, I would like to pitch in!

**Comment by iadeelzafar** [comment]
🙌 Hey @droid-it . Welcome to ChatAir. Yes, feel free to pick this issue. You might want to give our contribution guidelines in README a look before starting.

**Comment by iadeelzafar** [comment]
Just a quick suggestions for working on this screen, you'll have to use **ConstraintLayout** and set **constraints** in order to build a responsive UI on different screens. Good Luck!

**Comment by droid-it** [comment]
Thank you! Sure, will go through the guidelines and ConstraintLayout it is!
