### ISSUE TITLE
Implement Splash Screen 

### ISSUE THREAD

**Issue by iadeelzafar** [ChatAir/ChatAir-android#4]
**Description:**
Implement splash screen. Use the splash screen design from the [designs ](https://github.com/ChatAir/ChatAir-android/tree/master/designs)folder as a reference.

**Comment by galihsatriawan** [comment]
I have added splash screen like the design requirement, please check it

**Comment by iadeelzafar** [comment]
This ticket is up for grabs.

**Comment by AminullahTajMuhammad** [comment]
@iadeelzafar I am working on this UI screen
