### ISSUE TITLE
Implement Forgot Password Screen

### ISSUE THREAD

**Issue by iadeelzafar** [ChatAir/ChatAir-android#6]
**Description:**
Implement forgot password screen. Use the forgot password screen design from the [designs](https://github.com/ChatAir/ChatAir-android/tree/master/designs) folder as a reference.

**Comment by wale-bant** [comment]
Hi, I'd love to work on this.

**Comment by abdurahman-ctis** [comment]
I'd like to make it.

**Comment by iadeelzafar** [comment]
Welcome @abdurahman-ctis ! Please read contribution guidelines first in the readme. 
You can find the design for "Forgot Password Screen" in the designs folder.

**Comment by pfieffer** [comment]
Hey. I was going through this issue and I think we need to change the base application theme form `Theme.AppCompat.DayNight.NoActionBar` to `Theme.MaterialComponents.DayNight.NoActionBar` as many of the UI elements have rounded corners and the text input layouts have boxed outlines.
