### ISSUE TITLE
Implement Recent Chats Screen

### ISSUE THREAD

**Issue by iadeelzafar** [ChatAir/ChatAir-android#7]
**Description:**
Implement recent chats screen. Use the **Users Screen** design from the [designs ](https://github.com/ChatAir/ChatAir-android/tree/master/designs)folder as a reference.

**Comment by jalalkhademi** [comment]
Do you mean Users screen? I couldnt find any screen for recent chats.

**Comment by iadeelzafar** [comment]
@jalalkhademi yep. That's right.

**Comment by jalalkhademi** [comment]
Ok then I would like to take care of it.

**Comment by iadeelzafar** [comment]
@jalalkhademi you're most welcome. Please read contribution guidelines before starting. Also use Constraint Layout for the design in order to build. responsive UI for multiple screens.

**Comment by iadeelzafar** [comment]
@jalalkhademi Are you working on this?

**Comment by jalalkhademi** [comment]
Yes. I am going to finish it today.

**Comment by pfieffer** [comment]
Can I work on this or is it already completed?

**Comment by iadeelzafar** [comment]
This ticket is up for grabs.

**Comment by pfieffer** [comment]
@iadeelzafar Yes I would like to pick this up please.
I have some questions regarding to this issue:

1. So the **Recent Chats Screen** is depicted by the **Users Screen** in the designs folder, right?
2. Is static design going to suffice closing this issue or do I need to implement some sort of dynamic behavior with placeholder/ dummy data?
3. Are there any menu items on the overflow menu on the top-right  of toolbar, or is just having it is good for now?
4. What action for when the FloatingActionButton on the bottom-right is clicked?
5. I imagine there is some click listener for the list item. Am I right?

**Comment by iadeelzafar** [comment]
Hi @pfieffer 
We'd love your contributions. Feel free to take this up.

1- Yep
2- If you can add dummy data, that'd be great.
3- No menu items as of now but you can implement a menu for some dummy items.
4- FAB should open the Contacts Screen
5- Yeah, we can work with a ItemClickListener to open the specific Chat Screen for each user in the future. But for now you can just open the Chat Screen.

Let me know if you have any questions.

**Comment by pfieffer** [comment]
Also where can I find the overflow menu icon and FAB icon?

**Comment by pfieffer** [comment]
Yeah, I can find the overflow icon on the Android Studio Vector Asset.

I will be needing the icon for the FAB however. Thanks

**Comment by iadeelzafar** [comment]
@AminullahTajMuhammad should be able to provide you with the FAB icon very soon. :)

**Comment by pfieffer** [comment]
Hey, I have worked on this issue and all of the tasks are complete, except the FAB icon and its click listener. :)

**Comment by iadeelzafar** [comment]
Can you please open a PR so that we can start the review process? In the meantime, Amin will be able to provide you with the logo.

**Comment by pfieffer** [comment]
Sure :)

**Comment by AminullahTajMuhammad** [comment]
Sorry for the late reply. Here is the svg file of new chat icon [new-chat-icon.zip](https://github.com/ChatAir/ChatAir-android/files/4067526/chat-icon.zip)
