### ISSUE TITLE
Implement New Chat Screen

### ISSUE THREAD

**Issue by iadeelzafar** [ChatAir/ChatAir-android#8]
**Description:**
Implement new chat screen. Use the new chat screen design from the [designs ](https://github.com/ChatAir/ChatAir-android/tree/master/designs)folder as a reference.

**Comment by MaxHvesser** [comment]
Hi - I'll gladly work on this (: if it's still available?

**Comment by iadeelzafar** [comment]
Hi @MaxHvesser we are moving very quickly now and we want all these UIs to get done before 15 Oct. Do you think you'll be able to get this screen done and polished before that?

**Comment by MaxHvesser** [comment]
@iadeelzafar not a problem. This is a few hours work (I have time to do this today).  

Just to clarify, I will implement the screen as shown and create recycler row layouts for the chat messages, I won't however create the recycler adapter/view holders as this is likely suited to another (nn-ui specific) PR, is that fine with you?

**Comment by iadeelzafar** [comment]
@MaxHvesser yep. Right now we're just focusing on the UI and not functionality. Just make sure the UI is responsive. You'll have to use Constraint Layout and use constraints to set the views. If you agree with this, you're most welcome to start working.

**Comment by MaxHvesser** [comment]
@iadeelzafar absolutely fine with me, I'll start working 😉

**Comment by iadeelzafar** [comment]
@MaxHvesser I've assigned you this ticket. Good Luck!
